## Opdracht 

1-) arraylerde boyut onemlidir.
bir boyutlular vektor. daha fazlasi matristir..

In [1]:
import numpy as np

In [2]:
# 2-) 10 elemanli bir listeden olusturulan array 
a = np.array([1,2,3,4,5,6,7,8,9,1])

a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

In [3]:
# 3-) 10 * 10 luk matris
np.zeros((10,10) , dtype = 'int32')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
# 4-)birlerden, 10*10 luk matris 
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
# 5-) 9 lardan 10*10 luk matris
np.full((10,10),9)  
#### !!!! soru : Neden tip girdigimizde hata verdi. 
### tip girmedigimizde otomatik float yapmiyormuydu ?
### bu array in elemanlari integer..

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [6]:
# 6-) 5-25 arasi 3 er artan tek boyutlu array.
np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

In [7]:
# 7-) -1 ile 1 arasi 30 adet array.
np.linspace(-1,1,30)
### soru: 30 adet sayi iceren array diye mi ifade edilmek istendi.?? 
### array bu 30 adet sayiyi iceren tek boyutlu listenin adi degilmi??

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [8]:
# 8-) 0-30 arasi 5*6 lik matris..
np.random.randint(0,30,(5,6))

array([[28, 19, 24, 28,  9,  3],
       [ 4, 26, 15,  1, 16,  0],
       [12, 26,  3,  7, 28, 11],
       [28, 27,  4, 28,  5, 15],
       [17, 24, 20,  4,  0,  9]])

In [9]:
# 9-) kosegenleri 1 olan 10*10 luk matris
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
# 10-) 0-10 5*10 luk matrisin 
a = np.random.randint(0,10,(5,10))
a

array([[8, 9, 0, 6, 4, 7, 6, 7, 5, 9],
       [9, 5, 9, 6, 2, 7, 9, 9, 1, 4],
       [2, 8, 7, 7, 1, 5, 9, 9, 9, 1],
       [0, 5, 2, 0, 3, 9, 4, 3, 4, 6],
       [0, 8, 3, 2, 0, 2, 2, 2, 7, 7]])

In [11]:
# a-) size :eleman sayisi 
a.size

50

In [12]:
# b-) ndim : boyut sayisi 
a.ndim

2

In [13]:
# c-) shape : satir*sutun bilgisi
a.shape

(5, 10)

In [14]:
# d-) dtype : array veri tipi
a.dtype

dtype('int32')

In [15]:
# 11-) 0-10 3 adet 4*7 lik matris (3 boyutlu matris)
a = np.random.randint(10, size = (3,4,7))
a

array([[[2, 2, 4, 5, 6, 9, 3],
        [1, 5, 2, 2, 3, 2, 5],
        [8, 6, 4, 6, 3, 7, 9],
        [2, 1, 5, 5, 9, 9, 0]],

       [[4, 4, 7, 7, 8, 0, 0],
        [4, 6, 9, 1, 4, 8, 0],
        [1, 9, 4, 0, 8, 4, 0],
        [4, 4, 4, 0, 8, 7, 6]],

       [[2, 3, 5, 2, 0, 2, 5],
        [0, 3, 8, 7, 7, 3, 3],
        [6, 6, 1, 4, 1, 1, 2],
        [1, 8, 1, 6, 2, 4, 0]]])

In [16]:
# 12-) bir vektor olusturup matrise cevirelim.
vektor = np.arange(1,17) #1-17 arasi bir vektor.
matris = vektor.reshape(2,8) # 16 elemani oldugu icin matrise cevirebildik.!!!!!!!!!!!!!!
matris

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

### Birlestirme Islemleri 

In [17]:
import numpy as np

In [18]:
# 13-) 4 ayri vektoru birlestrerek bir array olusturalim.
a = np.array([9, 8, 7])
b = np.array([6, 5, 4])
c = np.array([3, 2, 1])
d = np.array([50130, 50131, 50132]) 
e = np.concatenate([a, b, c, d])
e

array([    9,     8,     7,     6,     5,     4,     3,     2,     1,
       50130, 50131, 50132])

In [19]:
# 14-) iki arrayi sutun bazli birlestirme.
a = np.array([[6, 3, 0], [9, 7, 5]])
np.concatenate([a, a], axis = 1 )

array([[6, 3, 0, 6, 3, 0],
       [9, 7, 5, 9, 7, 5]])

In [20]:
# 15-) Axis = 0 ve Axis = 1 arasindaki fark :
# Axis= 0 satir bazli 
# Axis= 1 sutun bazli birlestirme.

In [21]:
# 16-)Farkli boyutlardaki arrayleri satirve sutun bazli ayri ayri birlestirelim
a = np.array([4, 5, 6])  # tek boyutlu 
b = np.array([[2, 3, 4], 
              [6, 7, 8]])   # 2 boyutlu
np.vstack([a, b])

array([[4, 5, 6],
       [2, 3, 4],
       [6, 7, 8]])

In [22]:
# 17-) 10 elemanli listeyi numpy metodu ile bolerek 4 ayri array olstrlm.
a = [10, 34, 25, 68, 35, 76, 24, 90, 56, 72]
np.split(a, [2,5,8])

[array([10, 34]), array([25, 68, 35]), array([76, 24, 90]), array([56, 72])]

In [23]:
# 18-) Random bir array olusturup buyukten kucuge siralayip 
##{Python da sort ana elemani degistiriyor!!numpy da sort ana veriyi bozmuyor!}
## hangi elemanin hangi indexte oldugunu bulalim.
k = np.random.randint(0,20,8)
k

array([ 5, 12,  4,  1,  4, 10, 10, 15])

In [24]:
x = np.sort(k)
x[::-1]

array([15, 12, 10, 10,  5,  4,  4,  1])

In [25]:
# 19-) 20 elemanli vektorun 3., 5. ve 7. elemanlarina ulasalim.
z = np.random.randint(0,100,20)
z

array([21, 26, 37, 18, 85,  1, 97,  4, 67, 71, 65, 23, 86, 26, 73, 27, 72,
       74, 38, 50])

In [26]:
z[3]

18

In [27]:
z[5]

1

In [28]:
z[7]

4

In [29]:
# 20-) 10 elemanli bir vektorun 4. elemanini degistirelim.
j = np.random.randint(0,5,10)
j

array([3, 3, 3, 3, 3, 4, 0, 2, 0, 2])

In [30]:
j[4] = 18
j

array([ 3,  3,  3,  3, 18,  4,  0,  2,  0,  2])

In [31]:
# 21-) Diagonal matris kosegen elemanlari haric 
#diger elemanlari sifir olan matrise denir. 
#Bir matrisin Trace i o matrisin kosegen elemanlarinin toplamina denir(Square Matrix)

In [32]:
# 22-) 5*5 lik diagonal matris olusturalim. 
##kosegenine denk gelen sayilara ulasalim.
h = np.array([[3, 0, 0, 0, 0],
             [0, 8, 0, 0, 0],
             [0, 0, 7, 0, 0],
             [0, 0, 0, 2, 0],
             [0, 0, 0, 0, 5]])
h

array([[3, 0, 0, 0, 0],
       [0, 8, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 5]])

In [33]:
h[0,0]

3

In [34]:
h[1,1]

8

In [35]:
h[2,2]

7

In [36]:
h[3,3]

2

In [37]:
h[4,4]

5

In [38]:
# 23-) 10-20 vektor ve 3. indeksten son index e kadar olan elemanlari yazalim.
d = np.random.randint(10,20,10)
d

array([15, 16, 12, 15, 12, 11, 17, 14, 14, 10])

In [39]:
d[3:]

array([15, 12, 11, 17, 14, 14, 10])

In [40]:
# 24-) 10*10 luk bir matrise ulasalim. 
# a-) 3. satir 5. sutuna ulasalim.
s = np.random.randint(0, 100, (10,10))
s

array([[53, 39, 81, 50, 42, 54, 58, 76, 76, 38],
       [ 3, 20,  4, 86, 19,  8, 28,  5, 54, 37],
       [97, 90, 17, 96, 56, 85, 97, 37, 37, 45],
       [25,  1, 55, 39, 95, 14, 85,  3, 27, 85],
       [82, 58, 30, 62, 18, 93, 50, 59, 51, 51],
       [81, 38,  0, 76, 17,  2, 23, 94, 77, 63],
       [37, 91,  7, 99, 23, 20, 10, 11, 85, 64],
       [32, 89, 50, 11, 51,  1, 93,  3, 77, 72],
       [77, 69, 65, 54, 90, 28, 56, 42, 11, 60],
       [55, 79, 84, 38, 11, 70,  6,  1, 69, 87]])

In [41]:
s[3,5] # 3. satir 5. sutun elemani

14

In [42]:
# b-) 5. sutunun tum elemanlarina ulasalim
s[:,5]

array([54,  8, 85, 14, 93,  2, 20,  1, 28, 70])

In [43]:
 # c-) tum sutunlarin 2.satirlarina ulasalim.
s[2,:]

array([97, 90, 17, 96, 56, 85, 97, 37, 37, 45])

In [44]:
# d-) tum sutunlarin 2-7 arasindaki satirlarina  ulasalim
s[2:7,:]

array([[97, 90, 17, 96, 56, 85, 97, 37, 37, 45],
       [25,  1, 55, 39, 95, 14, 85,  3, 27, 85],
       [82, 58, 30, 62, 18, 93, 50, 59, 51, 51],
       [81, 38,  0, 76, 17,  2, 23, 94, 77, 63],
       [37, 91,  7, 99, 23, 20, 10, 11, 85, 64]])

In [45]:
# e-) satir 2-5 sutun 3-7
s[2:5,3:7]

array([[96, 56, 85, 97],
       [39, 95, 14, 85],
       [62, 18, 93, 50]])

In [46]:
# f-) satir 5: sutun :4
s[5:,:4]

array([[81, 38,  0, 76],
       [37, 91,  7, 99],
       [32, 89, 50, 11],
       [77, 69, 65, 54],
       [55, 79, 84, 38]])

In [47]:
# g-)g.	sutun indexi sadece 3, 6,9 olan sutunlarin tum satirlarina ulasalim
s[:,3::3]

array([[50, 58, 38],
       [86, 28, 37],
       [96, 97, 45],
       [39, 85, 85],
       [62, 50, 51],
       [76, 23, 63],
       [99, 10, 64],
       [11, 93, 72],
       [54, 56, 60],
       [38,  6, 87]])

In [48]:
# h-) 5,5 degerini degistirelim.
s[5,5] = 1991
s

array([[  53,   39,   81,   50,   42,   54,   58,   76,   76,   38],
       [   3,   20,    4,   86,   19,    8,   28,    5,   54,   37],
       [  97,   90,   17,   96,   56,   85,   97,   37,   37,   45],
       [  25,    1,   55,   39,   95,   14,   85,    3,   27,   85],
       [  82,   58,   30,   62,   18,   93,   50,   59,   51,   51],
       [  81,   38,    0,   76,   17, 1991,   23,   94,   77,   63],
       [  37,   91,    7,   99,   23,   20,   10,   11,   85,   64],
       [  32,   89,   50,   11,   51,    1,   93,    3,   77,   72],
       [  77,   69,   65,   54,   90,   28,   56,   42,   11,   60],
       [  55,   79,   84,   38,   11,   70,    6,    1,   69,   87]])

In [49]:
# 25-) 0-50 5 er artan array olusturalim
t = np.arange(0,50,5)
t

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [50]:
# a-) 20 den buyuk kac deger var
np.sum(t>20)

5

In [51]:
# b-) 30 dan kucuk kac deger var
np.sum(t<30)

6

In [52]:
# c-) 33 gecen deger
np.sum(t==33)

0

In [53]:
# d-) olusturulan arrayin tum elemanlarini 5 ile carpalim.
t*5

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [54]:
# e-) tum elemanlarinin 2 ile bolumunden kalan. 
t%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [55]:
# 26-) 0-1 arasinda 50 elemanli array. 
d = np.linspace(0,1,50)
d

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [56]:
# a-) ortalamasini  bulalim.
np.mean(d)

0.5

In [57]:
# b-) standart sapmasini bulalim.
np.std(d)

0.2945075446869757

In [58]:
# c-) varyans 
np.var(d)

0.086734693877551

In [59]:
# d-) median 
np.median(d)

0.5

In [60]:
# e-) en kucuk eleman
np.min(d)

0.0

In [61]:
# f-) en buyuk eleman
np.max(d)

1.0